from django.urls import path
from .views import (
    add_comment,
    comment_api,
    home,
    login_api,
    login_view,
    logout_api,
    me_api,
    post_detail,
    post_detail_api,
    create_post,
    delete_post,
    post_list_api,
    posts_api,
    reaction_api,
    react_post,
    register_api,
    update_post,
    register,
    verify_email_api,
    verify_email,
    forget_password,
    reset_password,
    verify_reset_code,
)

urlpatterns = [
    path('', home, name='home'),
    path('post/<int:id>/', post_detail, name='post_detail'),
    path('create/', create_post, name='create_post'),
    path('delete/<int:id>/', delete_post, name='delete_post'),
    path('update/<int:id>/', update_post, name='update_post'),
    path('register/', register, name='register'),
    path('verify_email/', verify_email, name='verify_email'),
    path('login/', login_view, name='login'),
    path('forgot_password/', forget_password, name='forgot_password'),
    path('reset_password/', reset_password, name='reset_password'),
    path('verify_reset_code/', verify_reset_code, name='verify_reset_code'),
    path('post/<int:id>/react/<str:reaction_type>/', react_post, name='react_post'),
    path('post/<int:id>/comment/', add_comment, name='add_comment'),
    path('api/posts/', post_list_api, name='post_list_api'),
    path('api/auth/register/', register_api, name='register_api'),
    path('api/auth/verify-email/', verify_email_api, name='verify_email_api'),
    path('api/auth/login/', login_api, name='login_api'),
    path('api/auth/logout/', logout_api, name='logout_api'),
    path('api/auth/me/', me_api, name='me_api'),
    path('api/v1/posts/', posts_api, name='posts_api'),
    path('api/v1/posts/<int:id>/', post_detail_api, name='post_detail_api'),
    path('api/v1/posts/<int:id>/comments/', comment_api, name='comment_api'),
    path('api/v1/posts/<int:id>/reaction/', reaction_api, name='reaction_api'),
]
